### ISSUE TITLE
Date Bug

### ISSUE THREAD

**Issue by alvaro2203** [Oskkital/ideas#3]
The date is updated with each page refresh.
Must always be the same date

Bug Example:
![image](https://github.com/Oskkital/ideas/assets/63745502/17ac693b-5bdb-4de7-a557-6e18c76f10ce)

![image](https://github.com/Oskkital/ideas/assets/63745502/988d5e7a-0791-4ae7-9dea-f762562a09c5)

**Comment by OscarGE11** [comment]
fixed update date.
