### ISSUE TITLE
checkbox bug

### ISSUE THREAD

**Issue by alvaro2203** [Oskkital/ideas#5]
when you click on the checkbox it changes the style of the card making it smaller. 

Example:

![image](https://github.com/Oskkital/ideas/assets/63745502/ace0d969-fa8a-49e4-9c99-e4cf28638db8)

![image](https://github.com/Oskkital/ideas/assets/63745502/5e1b378e-65b2-498c-890b-510f7bdb7712)

**Comment by OscarGE11** [comment]
Fixed checkbox bug fitting "completed" CSS class.
